[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version %}\
    {% if previous.version %}\
        ## [{{ version }}]($REPO/compare/{{ previous.version }}..{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
    {% else %}\
        ## {{ version }} ({{ timestamp | date(format="%Y-%m-%d") }})
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group }}
    {% for commit in commits %}
        {% if commit.scope %}
            * **{{ commit.scope }}:** {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }}))
        {% else %}
            * {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }}))
        {% endif %}
        {% if commit.breaking %}
            * **BREAKING CHANGE:** {{ commit.breaking_description }}
        {% endif %}
        {% if commit.body %}
            {{ commit.body }}
        {% endif %}
    {% endfor %}
{% endfor %}\n
"""

footer = """
<!-- generated by git-cliff -->
"""

trim = true
postprocessors = [
    { pattern = '\$REPO', replace = "https://github.com/Moukrea/gommit" }
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^chore", group = "Chores", skip = true },
    { message = "^docs", group = "Documentation", skip = true },
    { message = "^style", group = "Style", skip = true },
    { message = "^refactor", group = "Refactor", skip = true },
    { message = "^perf", group = "Performance", skip = true },
    { message = "^test", group = "Tests", skip = true }
]

filter_commits = true
tag_pattern = "[0-9]*"
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
link_parsers = [
    { pattern = "#(\\d+)", text = "#$1", link = "$REPO/issues/$1" },
    { pattern = "@([\\w-]+)", text = "@$1", link = "https://github.com/$1" }
]