[changelog]
# Conventional header
header = """
# Changelog

All notable changes to this project will be documented in this file.\n
"""
# Body template following conventional-changelog format
body = """
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]({{ compare_url }}) ({{ timestamp | date(format="%Y-%m-%d") }})
    {% else %}\
        ## {{ version | trim_start_matches(pat="v") }} ({{ timestamp | date(format="%Y-%m-%d") }})
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group }}
    {% for commit in commits %}
        {% if commit.breaking %}
            * **BREAKING CHANGE:** {{ commit.message }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit_url }}/{{ commit.id }}))
        {% else %}
            {% if commit.scope %}
                * **{{ commit.scope }}:** {{ commit.message }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit_url }}/{{ commit.id }}))
            {% else %}
                * {{ commit.message }} ([{{ commit.id | truncate(length=7, end="") }}]({{ commit_url }}/{{ commit.id }}))
            {% endif %}
        {% endif %}
        {% if commit.body %}
            {{ commit.body }}
        {% endif %}
    {% endfor %}
{% endfor %}\n
"""

footer = """
<!-- generated by git-cliff -->
"""

trim = true
postprocessors = [
    { pattern = '{{ compare_url }}', replace = "https://github.com/OWNER/REPO/compare/{{ previous.version }}...{{ version }}" },
    { pattern = '{{ commit_url }}', replace = "https://github.com/OWNER/REPO/commit" },
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^chore\\(deps\\)", group = "Dependencies" },
    { message = "^chore\\(release\\):", skip = true },
    { message = "^chore", group = "Chores", skip = true },
    { message = "^style", group = "Styles", skip = true },
    { message = "^docs", group = "Documentation", skip = true },
    { message = "^test", group = "Tests", skip = true }
]

filter_commits = true
tag_pattern = "v[0-9]*"
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
link_parsers = [
    { pattern = "#(\\d+)", text = "#$1", link = "https://github.com/OWNER/REPO/issues/$1" }
]