name: Release

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Quality"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.CUSTOM_GH_TOKEN}}
          release-type: go